---
 - name: add zabbix key
   apt_key: url=http://repo.zabbix.com/zabbix-official-repo.key state=present
   when: zabbix_repo == 'zabbix.com'

 - name: add zabbix repo
   apt_repository: repo='deb http://repo.zabbix.com/zabbix/{{ zabbix_minor_version }}/debian/{{ ansible_lsb.codename }} main contrib non-free' state=present
   when: zabbix_repo == 'zabbix.com'

 - name: install zabbix server
   apt: name={{ item }} state={{ zabbix_server_state }}
   with_items:
    - zabbix-server-{{ zabbix_server_DBType }}
    - zabbix-frontend-php
    - php5-{{ zabbix_server_DBType }}
